[project]
name = "single-agent-and-multi-agent-reinforcement-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.0",
    "mlflow>=3.1.1",
]
